name = "solidity-detector-foundry"
homepage = "https://hummanta.github.io/solidity-detector-foundry"
repository = "https://github.com/hummanta/solidity-detector-foundry"
description = "Detects Solidity projects by verifying if a foundry.toml file exists in the specified path and if there is at least one .sol file in the directory."
language = "solidity"
kind = "detector"

targets = [
	"x86_64-unknown-linux-gnu",
	"aarch64-unknown-linux-gnu",
	"x86_64-apple-darwin",
	"aarch64-apple-darwin",
	"x86_64-pc-windows-msvc"
]
