version = "v0.1.4"

[artifacts.aarch64-unknown-linux-gnu]
url = "https://github.com/hummanta/solidity-detector-foundry/releases/download/v0.1.4/solidity-detector-foundry-v0.1.4-aarch64-unknown-linux-gnu.tar.gz"
hash = "05b304aec2ed64f89a97282411f124cf4315abf2e0e98f9f66844cb8a7019d9a"

[artifacts.x86_64-unknown-linux-gnu]
url = "https://github.com/hummanta/solidity-detector-foundry/releases/download/v0.1.4/solidity-detector-foundry-v0.1.4-x86_64-unknown-linux-gnu.tar.gz"
hash = "5bad9e5459a9c0578eb88f72ec33f05a772627c12b1ad762dbf94e9af4f9c73c"

[artifacts.aarch64-apple-darwin]
url = "https://github.com/hummanta/solidity-detector-foundry/releases/download/v0.1.4/solidity-detector-foundry-v0.1.4-aarch64-apple-darwin.tar.gz"
hash = "802c7ccd11fce5475df22c32421d9582708de269466b87560f1e800ebf15eec5"

[artifacts.x86_64-pc-windows-msvc]
url = "https://github.com/hummanta/solidity-detector-foundry/releases/download/v0.1.4/solidity-detector-foundry-v0.1.4-x86_64-pc-windows-msvc.tar.gz"
hash = "980d371e131dacb89a4c997b3246a33ddaaf40127c047fd1bc9328b856366224"

[artifacts.x86_64-apple-darwin]
url = "https://github.com/hummanta/solidity-detector-foundry/releases/download/v0.1.4/solidity-detector-foundry-v0.1.4-x86_64-apple-darwin.tar.gz"
hash = "411d14af481285eee121e1e93606b521f3dd8f52a25b7362d9087e8d9ddb179b"
