version = "v0.1.5"

[artifacts.x86_64-apple-darwin]
url = "https://github.com/hummanta/solidity-detector-foundry/releases/download/v0.1.5/solidity-detector-foundry-v0.1.5-x86_64-apple-darwin.tar.gz"
hash = "02ee23678acc8ecd0b29290e04233a7646dcf339dac16d4c112a1af0b0c3996b"

[artifacts.aarch64-apple-darwin]
url = "https://github.com/hummanta/solidity-detector-foundry/releases/download/v0.1.5/solidity-detector-foundry-v0.1.5-aarch64-apple-darwin.tar.gz"
hash = "039e24bfe00b9342ccec7b5a3a573cb0f6c506f18de8b45bc8e5d7d6915ba4fa"

[artifacts.aarch64-unknown-linux-gnu]
url = "https://github.com/hummanta/solidity-detector-foundry/releases/download/v0.1.5/solidity-detector-foundry-v0.1.5-aarch64-unknown-linux-gnu.tar.gz"
hash = "73b57d699c6dab1633acc104cb035fb912577026f0b459229b259361bf11b1c6"

[artifacts.x86_64-unknown-linux-gnu]
url = "https://github.com/hummanta/solidity-detector-foundry/releases/download/v0.1.5/solidity-detector-foundry-v0.1.5-x86_64-unknown-linux-gnu.tar.gz"
hash = "2785d634b068ee5e4ed318c083e64b1600df6b37d92be5774c662bab7612c79b"

[artifacts.x86_64-pc-windows-msvc]
url = "https://github.com/hummanta/solidity-detector-foundry/releases/download/v0.1.5/solidity-detector-foundry-v0.1.5-x86_64-pc-windows-msvc.tar.gz"
hash = "4179f56ace90e681953c0b2a6ff8e4ee97964c7469cb6eef9bad9082ebd8163c"
