version = "v0.1.1"

[artifacts.aarch64-unknown-linux-gnu]
url = "https://github.com/hummanta/solidity-detector-foundry/releases/download/v0.1.1/solidity-detector-foundry-v0.1.1-aarch64-unknown-linux-gnu.tar.gz"
hash = "d773838209556a6c54390f6d46b1c3e04e56a33c3a44c2bfec7eff5baf444385"

[artifacts.x86_64-apple-darwin]
url = "https://github.com/hummanta/solidity-detector-foundry/releases/download/v0.1.1/solidity-detector-foundry-v0.1.1-x86_64-apple-darwin.tar.gz"
hash = "507ed97364baaa28eb3903048f3574ec0ff10e7f3c6a5b3ddd9d445dcaf06f6d"

[artifacts.aarch64-apple-darwin]
url = "https://github.com/hummanta/solidity-detector-foundry/releases/download/v0.1.1/solidity-detector-foundry-v0.1.1-aarch64-apple-darwin.tar.gz"
hash = "6ece04ac42ce776528034903f833f8ff167c4526d3cc8d428c734fad530fe945"

[artifacts.x86_64-unknown-linux-gnu]
url = "https://github.com/hummanta/solidity-detector-foundry/releases/download/v0.1.1/solidity-detector-foundry-v0.1.1-x86_64-unknown-linux-gnu.tar.gz"
hash = "04a3871f51fbfc32beec0231f5b551510d71d36bec971e191da8ad201e9957de"

[artifacts.x86_64-pc-windows-msvc]
url = "https://github.com/hummanta/solidity-detector-foundry/releases/download/v0.1.1/solidity-detector-foundry-v0.1.1-x86_64-pc-windows-msvc.tar.gz"
hash = "69b62245f04d63da895464e85389fe941e635bc47d296fbcd4424996a1ac4230"
