version = "v0.1.2"

[artifacts.x86_64-unknown-linux-gnu]
url = "https://github.com/hummanta/solidity-detector-foundry/releases/download/v0.1.2/solidity-detector-foundry-v0.1.2-x86_64-unknown-linux-gnu.tar.gz"
hash = "1b8e4aa3bcce00cf80e95c76a12a2446a2749504512e6f48ed966e74c5d8d78e"

[artifacts.aarch64-unknown-linux-gnu]
url = "https://github.com/hummanta/solidity-detector-foundry/releases/download/v0.1.2/solidity-detector-foundry-v0.1.2-aarch64-unknown-linux-gnu.tar.gz"
hash = "8be7b8652e75a86bab178a8f3cbec6f69f6b55c46f9d86789c53faab447fc47c"

[artifacts.aarch64-apple-darwin]
url = "https://github.com/hummanta/solidity-detector-foundry/releases/download/v0.1.2/solidity-detector-foundry-v0.1.2-aarch64-apple-darwin.tar.gz"
hash = "1e24d0d8152e1721053fe23cfb2288a5ec2d6546e67b8b308ea16e716165db15"

[artifacts.x86_64-pc-windows-msvc]
url = "https://github.com/hummanta/solidity-detector-foundry/releases/download/v0.1.2/solidity-detector-foundry-v0.1.2-x86_64-pc-windows-msvc.tar.gz"
hash = "e708bfecf14dd8d94135c45598f1627359e76dbe236649815cea03f6ce475ffb"

[artifacts.x86_64-apple-darwin]
url = "https://github.com/hummanta/solidity-detector-foundry/releases/download/v0.1.2/solidity-detector-foundry-v0.1.2-x86_64-apple-darwin.tar.gz"
hash = "6a590a52c8c541dc268a34627c8d32c87995124cc712ce5a1d8ce33e0d39ebbd"
